### ISSUE TITLE
Cant install

### ISSUE THREAD

**Issue by saiidabs** [yourtion/YXWaveView#1]
cant install your pod, i get this 

[!] Unable to find a specification for `YXWaveView`

**Comment by yourtion** [comment]
I can install. 

![screen shot 2016-12-06 at 11 10 16 pm](https://cloud.githubusercontent.com/assets/1475301/20930674/4f926e70-bc09-11e6-91a5-8cca3d6c59fc.png)

Please check your pod file.

```
target 'DemoWaveView' do
  use_frameworks!
  pod 'YXWaveView'
  # Pods for DemoWaveView
end
```

**Comment by saiidabs** [comment]
do i have to specify the verison ?
pod 'YXWaveView', '~> 0.3.0'

**Comment by saiidabs** [comment]
Sorry for the trouble , my repo was broke , all i had to do was update it.
http://blog.cocoapods.org/Repairing-Our-Broken-Specs-Repository/

**Comment by yourtion** [comment]
OK.I have update 0.4.0 to support Swift 3
